name = "dictation-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "9333c5987bace0a81c955dbf421a0d7b"
workers_dev = true

[[routes]]
pattern = "dictation-worker.jowge.workers.dev/api/*"

[vars]
BAIDU_API_KEY = "b70dYzEyj2rboam3CdV0OwbW"
BAIDU_SECRET_KEY = "HmVn05u5N7waKqUbzRsrnYyV96XULpgS"
